env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  import/resolver:
    typescript: # this loads <rootdir>/tsconfig.json to eslint
      alwaysTryTypes: true
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  import/extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
  react:
    pragma: React
    version: detect
rules:
  array-bracket-spacing:
    - error
    - always
    -
      objectsInArrays: false
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always